## combine company data and common data

In [1]:
import datetime, time
from datetime import date

import pandas as pd
import numpy as np
import os
import sys

from sklearn.preprocessing import StandardScaler

In [2]:
module_path = os.path.abspath(os.path.join('.')) 
sys.path.append(module_path+"\\data\\constant")

from constants import COMPANY_CODE

In [3]:
def locate_nan(df):
    idx, idy = np.where(pd.isnull(df))
    result = np.column_stack([df.index[idx], df.columns[idy]])
    return result

# return format
''' 
[[datetime.date(2022, 1, 17) 'dji_cr']
 [datetime.date(2022, 1, 17) 'dji_f_cr']
 ...
 [datetime.date(2023, 5, 23) 'kosdaq_cr']
 [datetime.date(2023, 5, 23) 'kosdaq_cr_2']]
'''

" \n[[datetime.date(2022, 1, 17) 'dji_cr']\n [datetime.date(2022, 1, 17) 'dji_f_cr']\n ...\n [datetime.date(2023, 5, 23) 'kosdaq_cr']\n [datetime.date(2023, 5, 23) 'kosdaq_cr_2']]\n"

In [4]:
code = COMPANY_CODE

# code = {'005930': ['삼성전자', 'sec'], '005380': ['현대차', 'hyunmotor'],
#                  '035420': ['NAVER', 'naver'], '033780': ['KT&G', 'ktng']}
# code = {'005930': ['삼성전자', 'sec'], '000660': ['SK하이닉스', 'skhynix']}
# code = {'302440': ['SK바이오사이언스', 'skbio']}

In [5]:
directory_for_predict = './data/data_for_ml/predict/'
pkl_common_directory = './data/common_pkl/'
pkl_directory = './data/common_pkl/'

In [6]:
df_common = pd.read_pickle(directory_for_predict + '0_df_common.pkl')

In [7]:
for key, val in code.items():
    df_company = pd.read_pickle(directory_for_predict + f'df_{val[1]}_company.pkl')
    df_company = df_company.merge(df_common, how='left', left_index=True, right_index=True)
    globals()[f'df_{val[1]}_combine'] = df_company.copy()

In [8]:
df_hyunmotor_combine.tail()

,retail_1,foreigner_1,institution_1,financial_1,invtrust_1,pension_1,privequity_1,bank_1,insurance_1,financeetc_1,...,ixk_cr,ixk_cr_2,ixtr_cr,ixtr_cr_2,ixut_cr,ixut_cr_2,nbi_cr,nbi_cr_2,bkx_cr,bkx_cr_2
2025-12-22,-2.09132,-6.71867,-2.33991,0.96317,-1.40914,-0.69948,-1.47435,-1.35714,-1.35846,-1.0000,...,1.80%,3.51845,0.38%,1.30766,0.67%,1.55496,2.41%,1.64926,1.14%,0.98321
2025-12-23,-2.89716,4.03506,0.03603,-0.07580,-0.52250,-0.60097,-0.27064,-2.80000,0.36052,-1.0000,...,0.46%,2.27143,0.99%,1.36693,0.45%,1.12279,1.50%,3.95199,1.24%,2.39770
2025-12-24,0.29434,-0.41866,-1.25114,-1.37043,-3.26444,5.93041,11.66326,-0.40741,-1.02629,-1.0000,...,0.99%,1.45307,-0.73%,0.25042,0.09%,0.54586,-0.35%,1.14203,-0.07%,1.16715
2025-12-26,-0.84176,0.15049,-5.95129,-0.05814,-7.14362,-2.12983,-0.92755,-13.00000,148.52000,-inf,...,0.17%,1.15646,0.42%,-0.30775,0.24%,0.32760,0.69%,0.33619,0.71%,0.63914
2025-12-29,8.02905,0.43972,-1.57685,-0.00896,-1.26786,-1.09527,-3.24682,-1.25000,-0.87908,-0.6945,...,0.07%,0.23661,-0.13%,0.29781,-0.03%,0.20970,-0.59%,0.09804,-0.08%,0.62765

In [9]:
df_hyunmotor_combine.index[0]

datetime.date(2022, 1, 7)

In [10]:
col_inv1 = ['retail_1', 'foreigner_1', 'institution_1', 'financial_1', 'invtrust_1', 'pension_1', 'privequity_1', 
            'bank_1', 'insurance_1', 'financeetc_1', 'corporateetc_1', 'foreigneretc_1']
col_inv2 = ['retail_2', 'foreigner_2', 'institution_2', 'financial_2', 'invtrust_2', 'pension_2',
            'privequity_2', 'bank_2', 'insurance_2', 'financeetc_2', 'corporateetc_2', 'foreigneretc_2']

In [11]:
col_his1 = ['open_1', 'high_1', 'low_1', 'close_1', 'vol_1']
col_his2 = ['open_2', 'high_2', 'low_2', 'close_2', 'vol_2']

In [12]:
col_common1 = ["dji_cr", "dji_f_cr", "dxy_cr", "ixic_f_cr", "bond_kor_10_cr", "bond_kor_2_cr", "kosdaq_cr", "kospi_cr", 
         "krw_cr", "ixic_cr", "spx_f_cr", "sox_cr", "spx_cr", "bond_usa_10_cr", "bond_usa_2_cr", "bond_usa_3m_cr", 
         "vix_cr", "wti_cr", "spsy_cr", "spny_cr", "spxhc_cr", "splrcd_cr", "splrci_cr", "splrcu_cr", "splrcs_cr",
         "splrct_cr", "splrcl_cr", "splrcm_cr", "ixbk_cr", "ixfn_cr", "ixid_cr", "ixis_cr", "ixk_cr", "ixtr_cr",
         "ixut_cr", "nbi_cr", "bkx_cr"]
col_common2 = ["dji_cr_2", "dji_f_cr_2", "dxy_cr_2", "ixic_f_cr_2", "bond_kor_10_cr_2", "bond_kor_2_cr_2", "kosdaq_cr_2", "kospi_cr_2",
         "krw_cr_2", "ixic_cr_2", "spx_f_cr_2", "sox_cr_2", "spx_cr_2", "bond_usa_10_cr_2", "bond_usa_2_cr_2", "bond_usa_3m_cr_2",
         "vix_cr_2", "wti_cr_2", "spsy_cr_2", "spny_cr_2", "spxhc_cr_2", "splrcd_cr_2", "splrci_cr_2", "splrcu_cr_2",
         "splrcs_cr_2", "splrct_cr_2", "splrcl_cr_2", "splrcm_cr_2", "ixbk_cr_2", "ixfn_cr_2", "ixid_cr_2",
         "ixis_cr_2", "ixk_cr_2", "ixtr_cr_2", "ixut_cr_2", "nbi_cr_2", "bkx_cr_2"]

In [13]:
col_cr = ['weekday', 'cr_00', 'cr_05', 'cr_10', 'cr_15', 'cr_20']

In [14]:
col_col = col_inv1 + col_common1 + col_his1 + col_inv2 + col_common2 + col_his2 + col_cr

In [15]:
# # write common data only
# df_temp = df_common.copy()
# df_temp = df_temp[col_common1+col_common2]
# pkl_common_directory = './data/common_pkl/'
# df_temp.to_pickle(pkl_common_directory + 'df_common.pkl')
# df_temp.to_csv(pkl_common_directory + 'df_common.csv')

In [16]:
new_columns = col_col

In [17]:
# column 순서 변경 : weekday, 'cr_00', 'cr_05', 'cr_10', 'cr_15', 'cr_20' column을 마지막으로 이동 
for key, val in code.items():
    globals()['df_{}_combine'.format(val[1])] = globals()['df_{}_combine'.format(val[1])][new_columns]

In [18]:
'''
# drop inf, -inf : replace inf to 1 or -1 . 데이터를 살리고
# 변동률이 무한대가 되는 것을 방지하기 위해서, 나중에 발생하는 에러를 방지
df_sec_sel.replace([np.inf, -np.inf], [1, -1], inplace=True)

.impute 사용하는 것을 고려할 필요 있음.
'''

'\n# drop inf, -inf : replace inf to 1 or -1 . 데이터를 살리고\n# 변동률이 무한대가 되는 것을 방지하기 위해서, 나중에 발생하는 에러를 방지\ndf_sec_sel.replace([np.inf, -np.inf], [1, -1], inplace=True)\n\n.impute 사용하는 것을 고려할 필요 있음.\n'

In [19]:
# drop inf, -inf : replace inf to 1 or -1 . 데이터를 살리고
# 변동률이 무한대가 되는 것을 방지하기 위해서, 나중에 발생하는 에러를 방지
for key, val in code.items():
    globals()['df_{}_combine'.format(val[1])].replace([np.inf, -np.inf], [1, -1], inplace=True)

# **** 데이터 전처리 from sklearn.impute import SimpleImputer, SimpleImputer 사용하기로 함.

In [20]:
df_sec_combine.tail()

,retail_1,foreigner_1,institution_1,financial_1,invtrust_1,pension_1,privequity_1,bank_1,insurance_1,financeetc_1,...,high_2,low_2,close_2,vol_2,weekday,cr_00,cr_05,cr_10,cr_15,cr_20
2025-12-22,14.78860,6.80743,2.83902,28.11704,-0.56392,-1.49396,-3.67073,-175.50000,0.33486,-8.76190,...,0.01480,0.02708,-0.01483,0.16233,4,1,1,1,1,1
2025-12-23,-3.55830,-2.10664,2.34675,1.50334,-1.15886,-3.55786,-1.78359,-3.33524,-0.56576,-2.53374,...,0.02126,0.03406,0.02695,0.21587,0,1,1,0,0,0
2025-12-24,-0.45492,-0.24706,-0.74197,-0.73049,11.02784,-0.78880,-0.11301,-1.12638,1.02512,-1.25600,...,0.02552,0.03955,0.04892,-0.21213,1,0,0,0,0,0
2025-12-26,-0.75169,-0.91499,-0.06522,-0.22704,-1.59793,1.97626,-0.68196,-3.73786,-0.78551,0.21875,...,0.01719,0.01464,0.00543,-0.49745,2,1,1,1,1,1
2025-12-29,7.72547,23.49710,1.42293,1.01701,5.53770,0.88597,9.80465,0.72695,16.16950,0.00000,...,0.04000,0.01812,0.04933,0.66599,4,0,0,0,0,0

In [21]:
nanlo = locate_nan(df_sec_combine)  # nan 위치 찾기

In [22]:
print(nanlo)

[[datetime.date(2022, 1, 18) 'dji_cr']
 [datetime.date(2022, 1, 18) 'dji_f_cr']
 [datetime.date(2022, 1, 18) 'dxy_cr']
 ...
 [datetime.date(2025, 12, 26) 'bond_kor_10_cr_2']
 [datetime.date(2025, 12, 29) 'bond_kor_10_cr']
 [datetime.date(2025, 12, 29) 'bond_kor_10_cr_2']]

In [23]:
# delete rows which include NaN : dji, spx, nasdaq 기타 common 지수중 한개라도 nan인 rows 제거
for key, val in code.items():
    globals()['df_{}_combine'.format(val[1])].dropna(inplace=True)

In [24]:
# string column을 numeric으로 전환
def string_to_num(df):
    df.replace('%', '', regex=True, inplace=True)
    df = df.apply(pd.to_numeric)
    return df

for key, val in code.items():
    globals()['df_{}_combine'.format(val[1])] = string_to_num(globals()['df_{}_combine'.format(val[1])])

In [25]:
# pickle로 데이터 저장

for key, val in code.items():
    globals()[f'df_{val[1]}_combine'].to_pickle(directory_for_predict + f'df_{val[1]}_combine.pkl')
    globals()[f'df_{val[1]}_combine'].to_csv(directory_for_predict + f'df_{val[1]}_combine.csv')